# Generated by hand for TanPit west-row grants

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pits", "0001_initial"),
    ]
    operations = [
        migrations.AddField(
            model_name="pit",
            name="version",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ColumnGrant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grants",
                        to="pits.user",
                    ),
                ),
                (
                    "pit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grant",
                        to="pits.pit",
                    ),
                ),
            ],
        ),
    ]
